MvcHTPC/ViewModels/CommunityViewModel.cs
using MvcHTPC.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcHTPC.ViewModels
{
    public class CommunityViewModel
    {
        public List<ForumDto> forumDtos { get; set; }
        public List<FolderDto> folderDtos { get; set; }
        public ContentDto contentDto { get; set; }
        
        public CommunityViewModel()
        {
            this.forumDtos = new List<ForumDto>();
            this.folderDtos = new List<FolderDto>();
        }

    }

}

MvcHTPC/ViewModels/ForumViewModel.cs
using MvcHTPC.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcHTPC.ViewModels
{
    public class ForumViewModel
    {
        public List<FolderDto> folderDtos { get; set; }
        public string lastModifiedUsername { get; set; }
        public ForumViewModel()
        {
            this.folderDtos = new List<FolderDto>();
            this.lastModifiedUsername = "";
        }
    }
}

MvcHTPC/Controllers/CommunityController.cs
using MvcHTPC.DTOs;
using MvcHTPC.Models;
using MvcHTPC.Services;
using MvcHTPC.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcHTPC.Controllers
{
    public class CommunityController : Controller
    {
        
        public ActionResult Index()
        {
            CommunityViewModel viewModel = new CommunityViewModel();
            CommunityService communityService = new CommunityService();
            viewModel.forumDtos = communityService.GetForumDtos();
            
            return View(viewModel);
        }
        [HttpGet]
        public ActionResult Notifier()
        {
            NotificationService noteService = new NotificationService();
            NotificationViewModel viewModel = new NotificationViewModel();
            viewModel.notificationDtos = noteService.GetLastMinutesNotifications();
            return Json(new {notes = viewModel}, JsonRequestBehavior.AllowGet);
        }
        [AllowAnonymous]
        public PartialViewResult _NotifierPartial()
        {
            return PartialView("_NotifierPartial");
        }

        public ActionResult Forum(string id)
        {
            ForumViewModel viewModel = new ForumViewModel();
            ForumService forumService = new ForumService();
            long t_forumId = Convert.ToInt64(id);
            viewModel.folderDtos = forumService.GetForumFolderDtosByDate(t_forumId);
            return View(viewModel);
        }
    }
}

MvcHTPC/Views/Community/Forum.cshtml
@model MvcHTPC.ViewModels.ForumViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

[Create New Folder]

<div style="border: 1px solid #000; margin: 5px; padding: 5px; border-radius: 5px;">
    <table class="table table-condensed table-hover">
        
            @if (Model.folderDtos.Count() > 0)
            {
                <thead>
                    <tr>
                        <th class="col-sm-1" style="min-width: 32px;"></th>
                        <th class="col-md-4" style="width: 100%;"></th>
                        <th class="col-sm-1" style="min-width: 150px;"></th>
                    </tr>
                </thead>
                <tbody style="border-bottom: 1px solid #000;">
                    @foreach (var i in Model.folderDtos)
                {

                        <tr>
                            <th style="border-left: 1px solid #000; border-right: 1px solid #000;">
                                <img src="@i.iconText" />
                            </th>
                            <td style="border-left: 1px solid #000; border-right: 1px solid #000;">
                                <p>
                                    <strong><a href='@Url.Action("Folder", "Folders", new { id = i.id })'>@i.title</a></strong>
                                </p>
                                <p>
                                    <span>@i.description</span>
                                </p>
                            </td>
                            <td style="border-left: 1px solid #000; border-right: 1px solid #000;">
                                <p>
                                    <span>Last activity @i.lastModified by @Model.lastModifiedUsername</span>
                                </p>
                            </td>

                        </tr>
                    }
                </tbody>
            }
            else
            {
                <tr><td><span>There are no folders here</span></td></tr>
            }
    </table>
</div>

MvcHTPC/Views/Community/Index.cshtml
@model MvcHTPC.ViewModels.CommunityViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="border: 1px solid #000; margin: 5px; padding: 5px; border-radius: 5px;">
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th class="col-sm-1" style="min-width: 32px;"></th>
                <th class="col-md-4" style="width: 100%;"></th>
                <th class="col-sm-1" style="min-width: 150px;"></th>
            </tr>
        </thead>
        <tbody  style="border-bottom: 1px solid #000;">
            @foreach (var item in Model.forumDtos)
            {
                <tr>
                    <th>
                        <span class="glyphicon glyphicon-question-sign" style="font-size: 64px;"></span>
                    </th>
                    <td style="border-left: 1px solid #000; border-right: 1px solid #000;">
                        <p>
                            <h4><a href='@Url.Action("Forum", "Community", new { id = @item.id })'>@item.title</a></h4>
                            <span>@item.description</span>
                        </p>
                    </td>
                    <td>
                        @if (Model.contentDto != null)
                        {
                        <p>
                            <span>
                                <a href='@Url.Action("Index", "Folder", new { id = Model.contentDto.folderId, content = Model.contentDto.id })'>@Model.contentDto.title</a>
                            </span>
                        </p>
                        <p>
                            <span>@Model.contentDto.dateOfCreation</span>
                        </p>
                        }
                        else
                        {
                            <p>
                                <span>
                                    No new activity
                                </span>
                            </p>
                            <p>
                                <span>-</span>
                            </p>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MvcHTPC/Views/Community/_NotifierPartial.cshtml
@if (User.Identity.IsAuthenticated)
{
    <script>
        var htpc_notifierTimer = null;
        jQuery(window).ready(function () {
            
            htpc_notifierTimer = setTimeout("notifierApplet()", 5000);
            
        });

        var t;

        var notifierApplet = function () {

            if (htpc_notifierTimer != null) {
                clearTimeout(htpc_notifierTimer);
                htpc_notifierTimer = setTimeout("notifierApplet()", 5000);
            }
            d("polling...");

            var r = new XMLHttpRequest();
            r.open('Get', 'Community/Notifier');
            r.onreadystatechange = function () {
                if (r.readyState == 4) {
                    var json = JSON.parse(r.responseText);
                    t = json;
                    console.log(json);
                    for (var i = 0; i < json.notes.notificationDtos.length; i++) {
                        iAddDialog(json.notes.notificationDtos[i].title, json.notes.notificationDtos[i].message);
                    }
                }
            }
            r.send();
        }
    </script>
}